before_install:
- chmod 777 cd/before-deploy.sh
- cd/before-deploy.sh
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.yarn-cache"
  - "$HOME/.sonar/cache"
language: java
install: true
jdk:
- openjdk8
stages:
- test
- deploy
addons:
  sonarcloud:
    organization: joquijada-github
jobs:
  include:
  - stage: test
    name: Test the Code
    script: mvn clean package -P coverage sonar:sonar
    if: type IN (push, pull_request)
  - stage: deploy
    name: Deploy to Maven Repo
    script:
    - yarn global add https://github.com/conveyal/maven-semantic-release.git#e5551beb4ec266bb520ae5ff155bc0d04acf8f05
      semantic-release@15
    - mvn package -Dmaven.test.skip=true
    - semantic-release --prepare @conveyal/maven-semantic-release --publish @semantic-release/github,@conveyal/maven-semantic-release
      --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release
      --verify-release @conveyal/maven-semantic-release --use-conveyal-workflow
    if: branch = master
sudo: false
env:
  global:
  - secure: AUemT5AX6g/COGr8+kSUCCIT39jrXBjkIeVFD3JEcEIBLxfwABZKZ6DfIwxS3figry++IMv+kIN7YrDXpg2DU0kh3AOCo+Uw2+SJWBPhXL32xHVTrtajXbRdyYLOpmZHE11Rm+VXEzZWuYx3ylPHkjAzvw4EIx/PYzA7jmBTU3Y9REdeAmy7S2JeICUtiJbS+CdOtN+l3r+btb5F7AkKZADJFGS3xgjqkX6a4PphlpJzFBkAbVWPFW9Z8EZE9+fmC+tBHC1E+2vPvG4hu3k3Awapc78e38wF1EcMuGZ0vmFpFdlOqaWfwmlxqXpmfp4S8rNpv4FgFIpDufKt+tdjjEL3nGTTKI45UnTfFhy5jYF/4a0DxfOZDvz4TLIsW0i0UquhFlnCxIihJsCPvqGpy75WykXesIxseE8Encq5cNKemnRyCAcS1HjgTmcZOLlb1ZXFOQO422eTSmnwX1ZwEL7aVD2lXohh5gzt8Toax80YFu5sWBTsEnYGl7YzmlTLfl4+q7vI6e2p4us3ZF8dYdQRuX+CbpasWvASAYo6M8zdIYFSci3voJS/TGb8/ThunVi1LR5mFFIrIA0OYX6zSP/vX0VDhoVL8pR0C98PkWiD/lyInFsiPlc6ysoq3M/1LTklfdzysZpxOdiXoNe12UwwoOiLLaJXLiI9SAL35Xc=
  - secure: akZxpGOVM4JqVBOIK7oy4o7Kc9e9declcmF/UJo+aUqcwm/emKNOttG6u2XemhtKogYBcdUXFSQL4MEc2kSFnW4tsz+oWD4GDwCHvLtxSk0hi47aCKvD+01q35XzRlyAxEqWFowqZpRp4Z36tEDXvIXktvlPbWWFmmBKI8iqMtK2srynQhEgdtfUVoA2AteIPceqoZcxiIdhjz1nDUpu/zpPGN6mzUatKpTf4my5gXuzk3ISXUQHFWW405MSBc5Qz6j47L7pWX8OcXHK12oOBeflTox43ouIUTGgCAUQc2AOTSyZOonK8ylys41SDwyW7VoK/GnHeCFIhjaJi0lrYSaEG9Rg3zAFhrD/Nx4h+DELEt2z2DEPNrZKXVBk9RI2swlscHj5FkfYgm6k/c/P1XH3NFSFmVwYB+B45ouGib2D+bmcyIIYH63c6Y0QB1aogmgQ26dUrOyJ6F8iI5pScSwfNS4/y+7HnPnBWhWUWcXZIYWZkhghXYyDl2SpmLHi8ZSudPDVwaSnXefEJsYyrB7JPsZ/GMtzfa+EEuIdZLGNZeEJgAM7Ss2n6BkK7ScWEGKQPMio31BFf8T1ybVbWg5o2yCaet2c0WKmLv83Ts/ywvBSTL3ZdmVxOWXSVl2rCMiiGLuw7SZjd30N4SN25D3kmKRx5vJxvXuPRfSe8eE=
  - secure: kYcR5LOqhq89yw/k00msaL0KSZTQ8uU9mokxkh+tNyy9NlLI1jCIPVf+19U21eVfzmq8KEcdkcn04KRsHPkrTSeik2uqX8g8BobZE6Yr7QkfgbFZ39vr7JTAw3YTztVBQWxZQj7hE/fZrdgzBt+VuY1ysZv9JkfhZwVtRK4nLkCIVdlTlW6e5scOQVPMfoeSICwX+TtwploBIK+buzJ/Gp3FtBzEZk6NOC3Q+3390bOrk6jPUni24vF3sqw02ziheWg0Qz3zH/VU5xbnx5iCpByuartaNZTwyw3hLp+FdXHbmKGh8q4EFmjJtiREwEBKaYHN/SfDNbsnrTH6BTe6u8tMYFD8ohk3vamCWRGHQd7bmLsTlUUMvzByTy9depIR2K6ZE1WxZYAq2RkgCNg9ftuovpGp9nCwzUaPS3ctqDB9Si/gzArU7/lb7s81LXXXEvkRNk/9XJpi7KGOZq7ty8Fy81QIoV/ZB4wnzg+3IR+izh9K+bOFuMIIO+zO0pKlHl4qQyvSqlh7JzfEbw+GGZxSdAyd4qTCxGby6iJ2UyTZ7hoQr9JydXwWYxkoWJ350/2uEJbb+25OgOKxQoAmz6JiJZJDXb3qkxFOAsFywapDUVssUHWPka2fqiHwRgg2Wk+jg6ExkMQcNPIsCMc1MtxprsIkyToYtdyI3IZnPWU=
  - secure: d7cI7F6rdfaFVrhAL0I8uC5dgG7JEOtyyedndDgt30EEisAoVqd+zlPcMu8LYbi/sDlIu0pl9dxyx7Dvv5RHPSdqp17jQvixKb9ypDh1j/YHUvtoudY+zsc0Y7ElwnK00KPKX0vZRevFSdaeumzRozLEtpeuYZpypT9MY2CLzgNvqLoOP//PmiqTsLnt6FUEmJNyhmZ74B4TjdeCIvVyPUxDfgKpNsrlHaV4xoby333+uzXOU7CD/XJAnfLkRf1nEsFZMr3uWR1Sx3nHrv4REukjevcL4TYFnKVBffZ8UMJOoxedCwiXwCa4n4BfZwCjoIh2ha7sIC3eRIUSU95fWWr4j3r8wc8NJL+qcBjj5KPhdY+eB4rIIvCgEIDTwtdPX7pwqLLC5kMa4MfhrnS6oogZsTRQ9H1I6/mPzxQq5XMoeSJ/Rnn95KjOGjj66NdgsHokTbcHe8YYCgsSVWTu963l1SdQA+ePUTvU32RYJpzFZvMeiqOU2OR7lvsit5m3ZNb0zhvzpco1ZaIs9qlWa6IKWMAzew9nCNXf5Da0+/5MfV4rPG0qKK7a09CcCeus6x6a63jGGTEwzoQsEE9WQ9PPcFqHVrSJi+C9RS3xdmeyb4f3Lz7Hymo4LEfv7XipyziAs66Xd5uok0A5IVvFvQ7dJEJvy+PkutCH/lFl9bY=
  -  secure: "sucgqa3hX2A7JNVK0rbyaNtdjkbgYCxvERF12goHLCXAETsbPCuLsvS8tt/CU2MsTrjob7psP1NJv4nxVV2/S9qwKYr9XRznFS/oK36iCdoUn/n8Sp4nZ7y6fRm1SdIeiIrRmEyckgVAoQp32PJUFTzXA7XL32SglqrYhmIMJzFYtpQhR56D0T8Tf+FE4I/Gaemu7ae9m09gbYTGbzeZ3x0bG0oadEUyt4ObBEuqqBjCtw0+bTLNeQY1vZOQmpcZrSqpUmXgZzPRYU5cjSvy1UHl0iOEUNsoRvVybY/B/QBpTmLPFcHQXhNJKC5fMrZOQQ+6bcty+86WIN0GxjdDYRh7xkuu+PeAob6f/j2UPUlMoS50OWLpHRIJf2D8g5DyhGXR0+HR17Z6HVTONtw1ELRktvaH1fkA636Kb5frMEJ7anMUddLlio3NiygMLX31jEDiQ5rRZbFUeEOoPZBImHP/OhaPttIw4cim7VbMcWmLn0F4wC680wF1TpAWPN4VcyCWzmrXVkPO+q5hrDR9STIt7/JSKib6sQJ8NA9x1U31+T0/fw7LIDy3RkGOhPw+Whhxea1PLXu9eTR11z56pIshdPQnT88OkZ1jUw4OWA2sz9BzoBpb7H3xxNCx1qZSxUaW1jB0UXkORmX50+IGBiJlZEY+l1jZZmbrMHF+NlQ="
