before_install:
- chmod 777 cd/before-deploy.sh
- cd/before-deploy.sh
- mvn install:install-file -Dfile=lib/ojdbc8.jar -DgroupId=com.oracle -DartifactId=ojdbc8 -Dversion=8 -Dpackaging=jar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.yarn-cache"
  - "$HOME/.sonar/cache"
language: java
install: true
jdk:
- openjdk8
stages:
- test
- deploy
addons:
  sonarcloud:
    organization: "joquijada-github"
jobs:
  include:
  - stage: test
    name: Test the Code
    script: mvn clean package -P coverage sonar:sonar
    if: type IN (push, pull_request)
  - stage: deploy
    name: Deploy to Maven Repo
    script:
    - yarn global add https://github.com/conveyal/maven-semantic-release.git#e5551beb4ec266bb520ae5ff155bc0d04acf8f05
      semantic-release@15
    - mvn package -Dmaven.test.skip=true
    - semantic-release --prepare @conveyal/maven-semantic-release --publish @semantic-release/github,@conveyal/maven-semantic-release
      --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release
      --verify-release @conveyal/maven-semantic-release --use-conveyal-workflow
    if: branch = master
sudo: false
env:
  global:
  - secure: eJjI6LM9dp3KRQCnMlN610demVzt7uJHZZZtP/+Eb+W7VPd3lQIi4tnfPqCkAA6nY1xHaAI1y0ojlBcPRRQfZoP3n9vVvpRbXdq3ZztIvR7q8mn1TFfMJ+dd6zpH3CEJtxmgCwrpp/1y+m9jMIpwYMpUXGGoWZizd+oMgRf6+9ixgvrNtIBurH5pG51ZEiYXIxnR73qhRsoGmZKzcvyTmdYT8a99hJckQEjm32UosBTTitlITv+JV9cGodyieWOr68ezGYfdB48XwY2r4rMfuWcUW8IaQ5tIbXBHZvLIj38k3XqM+qnQokPh1INOyVA55UGmgkAQLER671OEBZSW+qMHxhXweCCs0wwjzAm4gwS4Y/I4HV00DLSNr2R4p++RnIDkiUFfVS/ExkbroznuoTmTraX0xzEMOjHOWxcIth/fN+/NTj0fNL/lJSx87Hbpn774UojdRHSvuDMtIGGMiUSNyAzxyq8S2/FauaeqfQCmd1K5dMmspmiRm0J/bNLQGCht8RaXyQrxGFT5+rN676Vu0659Q1I7rsQ4IOO/VTYLgGMOVjqlkK6hUZ9DhadlnWDGAHKI6VIRq7hpp29P4ZAiWqIB0FO2NuzbzRFasY/JHAT3qoY7G5A8zaq/qbbRknN5AU952hnZJV0upQv/Hw2LXpsC9rWo0yOx9Wz5+hU=
  - secure: dZ2Uo+A4mv6r4aJGPyy98qyzSQfOpam7W1Olcz9o744rLLFq23ZcqU23ymvxp1yw6v+HuIzIgYF19W9DYikrblpJIdgbzXN+mJZ1GCySltIm0Nj5Ej+sgpRKmy1YO93pPT39wzX3pN/o5l4qOqgsK1PTVJweYuiRCF9iLfpq3JzzZulji8ivDHLmUeHwSlZyuoP87OUU37PpIRBkvpUDICrG5O/+PuqpfJD451CEQA0Ru9dw4DQwjybya9zPJdglOGF3FJUBNRYt2Ctya5SoiA8jCd/+HncRdXrSrM69P9rFBpBG85UJTpQtTXgVNxaHWBWJxVKmYnOLeNfSACHuqtzdT0tnTyA1sEQBZZvK3omkijtC8DUAi1gBtqhKzW6qrDmOE2ZshCZIYLei2TzlAb+/CSQe/LUR6d4nCDPSXNW53qUbLe9GCvWpTkYTTqH0lmylO1EjxjVFzp7FDZItcGnJktNYF2+plyGJZIsRbgFmd2xXNmAZdSJmftoy71M7rfJLzXbbCMpIX/R5zokPyFw4D2S/SiLTBiHRToyKUnmHVZ5t9MV6YS1oUiF78MWxM1UPXtZ0cVDkLBgj2zGiiqKZcHt47Ds+h0xUM7cRo8jo/8BJChqDhPteFmgZRYDUg23ij4L01dvt2fWIO34GL86pfWoBWN1jJkoOFCmhk30=
  - secure: DApth3v4KA8NBVmw0R+isjFzBt8Z1ZuMiwQXpgHkIveqrPOPWgVpY3PTwsaVRAWcrW4Zf+DGkQ1m5Af6hZrmtbgaJqlT+Nme3BeY82lmlS25AN76MDpIkDeF+CuWDC3MhXWDnyjCfPovdWQ1DYqZLZC039xrHHjYLEMDBdZD/CgmJ6LsTr19cCT9QMbWcukASms1ZKQV6H1SNt7gzo8Gq2iE5iLD+2It9kbgprGy0PsIQaaw+pNr4mXg7nikfiRT/5J+927Js6ZNZv14lLkpoT2U9y/oCJrG+jTIOO1h+4osNjfTrYubsHRhDlFxHAB9jDkfejqy79weND8rwtQcN7F1XorjCxbGyBimvP/i4sIiUSpDxIEadCNDImqJ95eGOcXJIaLvzEa/f8F5xcyypGed3hBAhY8GypXuumEdaulOIwgxCR0a/33QJOl7rMdBWtK/RVWYnmkZZSlZZyWGdhslGLgbeQL6tsBuFlq8m55IuYbSKfn60FBGswVhG+2kBkpwnJ/VWzfHcZ1JVIikQboleuTcnrK6FKNkD58MRLhptfZiTeWL+jhUJgarUWLlTc44/vnqQy9nZ5XCTpfC51MnC4vCZPJFrfWZJZf3s+5RUizu5igDys00Z6DVx2/0XfLlxUAyIpBzg5ohst1YwNYdL05nI6RN5ZUDjDRT5IY=
  - secure: VJ99vKAwloWJIP54u+CrEudnfrJrO7D2Kc77testt/Y1miEzXK+pjvtQ+e52ouC/i8ftcJWTypAZuxjGEU7IQiyvxkobRZiXkpjFhvGQG9zOtyuo0ihnPhNOob9n2SnIuEbgfbcmORoYbAosDTN0XM4qiIrquk8zELy0i6cA5OTpoyL+/jLmPTrcNscG5z1KjYc3iTmlOrnQ3+l0pNWOADaIMUpqI8bEqYADdf5tSKMgxMn0pt8O+Oro7wjcE3hT62fACjI4k+nfvJWkdv/nFoaAr3qeWHz/nP3TACsAQNCusa7C8ihbCek283O+y9xWzBYY07K3ySQ8i1ZM/TsPKLf4EBYVCnsZpqeEOeVNHcq2uxPiUo/w0+mawpV9qzeL3o9RF7DiDr2gNNAWBg0Uyws3hi6ZyMpk1Sne9TbkiuOwKUqzeGBO35gGzs/EzgEYDb3bTcSF0614jjoBGuPbjKIEGcisXQeIM5gbpolEwAPNybQTMgIDPMfu502AXaVVs32XiRXv3xqggHI4wSQK8Du3f/yJ7f6nzc//wu4lHO+xBlqiu/fxy++v85J5UriXHiEHsxMQhMt8QgCo/twsFM5SNwDX0lEwdudj8EkGL28ERz0X71VEsBUjotnRb/6mH/AAmDAqFgKFAuLjSZCYPdqprT24bwnU1bc6qSOkxaI=
