before_install:
- chmod 777 cd/before-deploy.sh
- cd/before-deploy.sh
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.yarn-cache"
  - "$HOME/.sonar/cache"
language: java
install: true
jdk:
- openjdk8
stages:
- test
- deploy
addons:
  sonarcloud:
    organization: joquijada-github
    token:
      secure: p8x0nz0vl6vTARgmoc+5ZRa2sTo+xJteoCzKgMhc1A/aH+zzxi/bfjIz2rw0/eVe6Plegv/abg4eZGQCijs1Me/nncIDSr8so/Szn90bWM5+pXPETIqxYmdkPQLB3vhuyKQyMPPhI0Dg2H2qzvD8Rf0oyn1Y7xyi9c7oJ+vif0ROqFVImqc+2++4CNhGHJBSG7misOBI2hRw5MVojYYKt3FZBsQiSFnjukXccQxBpXY5ZG/4GpZIM0w13poDXM2mBVbrDW4EaS59jNZRSr+YXpjLYq8i4Ki87AMUSuVYjE8sTVoZTtTJoGUhOauqfD/27UGhKLNT/Op5HZm/YG/0y5TZo+BODP2M+DP2IzXFk3k8YD07QmjO81grBNJmYXzPQjBf6EGzj2ZNFshUUPwzaO61RhuilPpp7g2oEk6toWnhAAy93jG6onCTa3U7jWYWm6bI+ER+6Ei0QLL8PAvMGG+fFZibmuDrjbYH7lQxSQw5OvhZY8OVrCwiv9jQ9wzWr42P/UB5n61cRfcLuUJH3Gc3s/fAQoC5NFe+7518QjnIoNzXZFhYJrzjgZaGom6wCSyziT0sYKwIebbTSnHdQlf0MvoYmo9fQqnnN7CqBGLZ3KRK3Y4uNMPJPaBjWt6guKAMERrVOr9yI9Jozx6UNx7YTUxhQvgvlqXbFagL+tQ=
jobs:
  include:
  - stage: test
    name: Test the Code
    script: mvn clean package -P coverage sonar:sonar
    if: type IN (push, pull_request)
  - stage: deploy
    name: Deploy to Maven Repo
    script:
    - yarn global add https://github.com/conveyal/maven-semantic-release.git#e5551beb4ec266bb520ae5ff155bc0d04acf8f05
      semantic-release@15
    - mvn package -Dmaven.test.skip=true
    - semantic-release --prepare @conveyal/maven-semantic-release --publish @semantic-release/github,@conveyal/maven-semantic-release
      --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release
      --verify-release @conveyal/maven-semantic-release --use-conveyal-workflow
    if: branch = master
sudo: false
env:
  global:
  - secure: HfRr25id/TKCOr+kIzugbeblsfUjZGw2EhmB2bR77To5aJanYyPhr2tsDxI9x0JIP+y3CsNn4RfeAitYu2f1UpdmhNzvVr0FVHS9h5CY2UNhvrq12vQful0pRGgwYr+DFsewMI46WzjPOXaD0IOmIvZdpbcprmgtfS+qAW93AfOpXXKAmlA7MRMn6Yxnngw8thgDKeYscRkBXhaXQ8gcOK3X07+XIIUdd7S7FQ1d4rHiis9QNNthouxsr0pJsmrRR3w/fR0Q++IgMVHwiRE1yQg60yszo8F5EG+PVzwzIEK9cac6sVQIRBys5cJI9E2O1eJLvbE9LznuV7Ln+nd/+t530IjH2BxuyuWJyZISkVvY+93Ma3lIoAcdDqTN9z/EDDAowyHLi7+/IXx/EDzS/d0YYj3/Ky6Mifnu33ZM0uZitJ6AO2gq5d/7yYAfcROilaLyEMqN0HPMy8UB/2sVSRJ0RebkZywarUvHRVyDdtAj5S2zAZ+OYuZb16H2/w6PJHCLbxf6hPiNCAyPFqFKqv3HVN1oKPfZTTY9Th+JETk1RgND5Jxsbaj5iZcQJLwPaLQjBkS9cIFR1D+P5PCbs3xDrxd7geaI0wgV+AL51lm7anGYZc8X1zWhpHT6dFA512dk6pxdHtw2hlU3rokODCVCIFyDueyt3B4M9iYfhyY=
  - secure: Up/2lgrWwBVcwEYo1nALFxxtnlvK6PVAIiXCr76KZ3UQ1sKivIH3M+sCwquqOidS4635RV9Q6vrQPG7fzNjrPanYgeBUdfO54wbg8pvjB5ODr/UnZ0cx196sfjQ/+sGvjW3Cg/Z1/jxEhZuo3jRLSc5ZaqJW9uvmzrRp0emQOSkxqDjCkeER/edp5gvYUOmXzMHGdzpBBXjr03aYcj5OX12UaYbsHYas5JyViJH7V2cRz96B/aaWgaWtj2faYKbZeKPGZfgKYngQXlHLqjn3G2Zz3E4Z52dYg4hivXEF6nwVQKp+1+W+MUY6ZA6TaNo5qf1GBtwLdj/B2dpsWLkpZ9NrwiZDFkeu/gn09JdDiXllXiEsuy62qQVF7hQsbesPKiQpF430VX8CngRg8mX1hyUhA46AlNWzDl5u4c9x3T0YB6a79McbYb4abnOeP2KjDraY47wafAf/6nz/8l8hTdprqPjulv7We0QMDTYgXzW9dPSrUgBYHOQkuw6vjlJjKGkTJn9ciiw50mP0zLzIMriZs16iGFSCsKp2kmWdhfBivE7bLjFweKu71u3X9SKo51GUQoQCYzw0t5JPesXE45dAny5yuTE7JBpneIaL2RbrletY7/7CO5oZ6ucvl+CyEghJ97fe04qQeprTpvIuLjvrsdxnc/4yBC169qsQsic=
  - secure: M4Xew4rC9/FysOIDsrTYIOb/gvFYzuS3K54pktxG8J/opV1Q62/pSbFLYfKLns8BCIEFDJLrvoc3+LqHHwJ20qDiAXY+WFKEXHD1ZRmPZWAthhYWqkWnnpZNVnLIpE7cc6JRBcNWdRV8VhQ1o6x9dH5ZH3giTISMD/Y7y4jJjfZRMC5Dx71puUcRk4EnETKKFrsZPniGnuKIP4UQOmD6Isy7qpFaioCA96RPbySDa/CtaWsPMz3H5lT8pXerZLhPWSwhhPwJMp4+Uga/aYOeO224sM2bgozz9fHMkUroaYwNimkZSovMrTyct7RI5+YUz+Ds9zoiHJkNZCiVyvMg3AQfWRexRiVLMZuj05yLJBuQLshEGdGVpVi06hKYFd/96hdamG/Ih1Qp+QAUy/EjEZ92sGyCkUUvxO/Mfh/pzzEYtqyFlhI+3aYy9JsRF1PP9I4ohfzoXVcO5acH7MGh7pVT9qIA4Tbd0iXe0o45OlKnsofB+yRUH6TCGGHX0SwyVPWdiHDgR4nFDw0F7rVfttb28ohdMdasP4zuDQcsRqFG3YUT6IvqMbtmiXcuTx/S4rWeaZhZM9FVd+C94Oe4g+u1aLsN1hSzlnNj00Dm7Qw+OXlajsiJ0gwv+i+jCFm3kjFHR8EF9rCMh4h+GK24eXm1BSZF6Ngt6dQTmSMk5so=
  - secure: IOck2Ifqjku7nzjtSduGMfQzmBEeqjzxBEpUATBvGgL1tdlNuKeGfFOzCrjiAEzABkI/5eRI3eBt+Df5v+n+kPITMUZK8SDnqy2Uh9b51zcg2XbH7lZnsEXDG1iF+GkpZnGyuuVt6wcYsnsMoPaMywQe/2bY9iEP+4MIWf0RCrCLEE5gl4rDAjTsX4IO17cuQJ8YoQPgstU/aZCzYF1+GrYspMtJBYYUqQxY3KE0N7qdmUQtPmGE13i6ORQiSd4CgCWcpeK1NezE22G4Pr1IHwLUoni5DZVL2Ytn+HElrS1dRYVkkQjmCmRh9wlj0ZvgMfI71tlSo1NlsQNTBn91eq/vY1lg0NROTHrzkBlAyQgy7WQgVutNPauQHnrG34H3bmxIiMvHrMVBu3W65MbQHP3u/pmBm+Bje5ypVxpXUkcObGx7dPFxowseNafq5G5NImlYZ9toLFh9aaIlWRiJHlj4JMyS9F3GLe8FNmrAMrzhrbDD0ul/CTvJRQdm4vzALVmr/Rij2Ecn9DIjUp+J1xju4embQ+80fvtWOe7ClHTazW1lYBGGs4S42jWGViE3M/E/seJsIV7MbgfuugV3NkYzwbD68w2q/kwHsiIGi9xDAZK5BQkxMC2/C17q1fEFks/IhiUFonSSlzoCfKSv71d6D1Tn7S0fz6vUnrQidic=
